# Generated by Django 4.2.6 on 2024-03-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dciudadano',
            fields=[
                ('idciudadano', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('roluniversitario', models.CharField(blank=True, max_length=100, null=True)),
                ('primernombre', models.CharField(max_length=100)),
                ('segundonombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primerapellido', models.CharField(max_length=100)),
                ('segundoapellido', models.CharField(blank=True, max_length=100, null=True)),
                ('solapin', models.CharField(blank=True, max_length=10, null=True)),
                ('carnetidentidad', models.CharField(blank=True, max_length=35, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=35, null=True)),
                ('residente', models.BooleanField(blank=True, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('idexpediente', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dciudadano',
            },
        ),
        migrations.CreateModel(
            name='Dexcepcion',
            fields=[
                ('idexcepcion', models.AutoField(primary_key=True, serialize=False)),
                ('ipmaquina', models.CharField(blank=True, max_length=20, null=True)),
                ('horaexcepcion', models.DateTimeField()),
                ('nombreaplicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('usuarioaplicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=5000, null=True)),
                ('seccion', models.CharField(blank=True, max_length=5000, null=True)),
                ('versionapp', models.CharField(blank=True, max_length=50, null=True)),
                ('nombrepc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'dexcepcion',
            },
        ),
        migrations.CreateModel(
            name='Didentbiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idciudadano', models.IntegerField(blank=True, null=True)),
                ('idbiometrico', models.UUIDField(unique=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'didentbiometrico',
            },
        ),
        migrations.CreateModel(
            name='Dnewsolapinhistorico',
            fields=[
                ('idhistorico', models.AutoField(primary_key=True, serialize=False)),
                ('idsolapin', models.IntegerField(blank=True, null=True)),
                ('numerosolapin', models.CharField(blank=True, max_length=7, null=True)),
                ('serial', models.CharField(blank=True, max_length=10, null=True)),
                ('codigobarra', models.CharField(blank=True, max_length=10, null=True)),
                ('idtiposolapin', models.IntegerField(blank=True, null=True)),
                ('nombrecompleto', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('roluniversitario', models.CharField(blank=True, max_length=100, null=True)),
                ('residente', models.BooleanField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('datatiposolapin', models.CharField(blank=True, db_comment='Tipo de solapin segun la transformacion rol universirario', max_length=255, null=True)),
                ('datacategoriasolapin', models.CharField(blank=True, db_comment='Categoria del solapin segun calsificacion rol universitario', max_length=255, null=True)),
                ('idciudadano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dnewsolapinhistorico',
            },
        ),
        migrations.CreateModel(
            name='Dordenimpresionhist',
            fields=[
                ('idordenimpresion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroorden', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateTimeField()),
                ('tipoorden', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dordenimpresionhist',
            },
        ),
        migrations.CreateModel(
            name='Dsolapinestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=10, null=True)),
                ('tiposol', models.IntegerField(blank=True, null=True)),
                ('descripcionsol', models.CharField(blank=True, max_length=50, null=True)),
                ('estadosol', models.IntegerField(blank=True, null=True)),
                ('descripcionestado', models.CharField(blank=True, max_length=25, null=True)),
                ('estadoreal', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudadano', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'dsolapinestado',
            },
        ),
        migrations.CreateModel(
            name='Dusuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=24, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dusuario',
            },
        ),
        migrations.CreateModel(
            name='ExtradateTemp',
            fields=[
                ('carnetidentidad', models.CharField(blank=True, max_length=255, null=True)),
                ('nombrecompleto', models.CharField(blank=True, max_length=255, null=True)),
                ('numexpediente', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('anoacademico', models.CharField(blank=True, max_length=255, null=True)),
                ('facultad', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipocurso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'extradate_temp',
            },
        ),
        migrations.CreateModel(
            name='Ncausaanulacion',
            fields=[
                ('identificadoranulacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ncausaanulacion',
            },
        ),
        migrations.CreateModel(
            name='Nestado',
            fields=[
                ('idestado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'nestado',
            },
        ),
        migrations.CreateModel(
            name='Nestadoordenimpresion',
            fields=[
                ('idestadoorden', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'nestadoordenimpresion',
            },
        ),
        migrations.CreateModel(
            name='Ntipoestadosolicitud',
            fields=[
                ('idestado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ntipoestadosolicitud',
            },
        ),
        migrations.CreateModel(
            name='Ntipohuellaciudadano',
            fields=[
                ('idtipohuella', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ntipohuellaciudadano',
            },
        ),
        migrations.CreateModel(
            name='Ntipooperacionsolapin',
            fields=[
                ('idtipooperacionsolapin', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'ntipooperacionsolapin',
            },
        ),
        migrations.CreateModel(
            name='Ntipopermiso',
            fields=[
                ('idtipopermiso', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('recurso', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ntipopermiso',
            },
        ),
        migrations.CreateModel(
            name='Ntiposolapin',
            fields=[
                ('idtiposolapin', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ntiposolapin',
            },
        ),
        migrations.CreateModel(
            name='Ntiposolicitudafis',
            fields=[
                ('idtiposolicitudafis', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ntiposolicitudafis',
            },
        ),
        migrations.CreateModel(
            name='Dimagenfacial',
            fields=[
                ('idciudadano', models.OneToOneField(db_column='idciudadano', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='captura_datos.dciudadano')),
                ('foto', models.BinaryField()),
                ('valida', models.BooleanField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dimagenfacial',
            },
        ),
        migrations.CreateModel(
            name='Dsolicitudimpresionhist',
            fields=[
                ('idsolicitudimpresion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('completado', models.CharField(max_length=1)),
                ('numeroorden', models.CharField(blank=True, max_length=30, null=True)),
                ('fechacierre', models.DateTimeField()),
                ('idciudadano', models.ForeignKey(db_column='idciudadano', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dciudadano')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dusuario')),
            ],
            options={
                'db_table': 'dsolicitudimpresionhist',
            },
        ),
        migrations.CreateModel(
            name='Dsolicitudimpresion',
            fields=[
                ('idsolicitudimpresion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroorden', models.CharField(blank=True, max_length=30, null=True)),
                ('fechainicio', models.DateTimeField()),
                ('idciudadano', models.ForeignKey(db_column='idciudadano', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dciudadano')),
                ('idestado', models.ForeignKey(blank=True, db_column='idestado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ntipoestadosolicitud')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dusuario')),
            ],
            options={
                'db_table': 'dsolicitudimpresion',
            },
        ),
        migrations.CreateModel(
            name='Dsolicitudafis',
            fields=[
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('idsolicitudafis', models.UUIDField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('idciudadano', models.ForeignKey(blank=True, db_column='idciudadano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dciudadano')),
                ('idntiposolicitudafis', models.ForeignKey(blank=True, db_column='idntiposolicitudafis', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ntiposolicitudafis')),
            ],
            options={
                'db_table': 'dsolicitudafis',
            },
        ),
        migrations.CreateModel(
            name='Dsolapin',
            fields=[
                ('idsolapin', models.AutoField(primary_key=True, serialize=False)),
                ('codigobarra', models.CharField(max_length=10)),
                ('numerosolapin', models.CharField(max_length=7, unique=True)),
                ('serial', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('idtiposolapin', models.ForeignKey(blank=True, db_column='idtiposolapin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ntiposolapin')),
            ],
            options={
                'db_table': 'dsolapin',
            },
        ),
        migrations.CreateModel(
            name='Dordenimpresion',
            fields=[
                ('idordenimpresion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroorden', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('tipoorden', models.CharField(blank=True, max_length=30, null=True)),
                ('idordenspdi', models.CharField(blank=True, max_length=40, null=True)),
                ('idestadoorden', models.ForeignKey(db_column='idestadoorden', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.nestadoordenimpresion')),
            ],
            options={
                'db_table': 'dordenimpresion',
            },
        ),
        migrations.CreateModel(
            name='Doperacionsolapin',
            fields=[
                ('idoperacionsolapin', models.AutoField(primary_key=True, serialize=False)),
                ('codigobarra', models.CharField(max_length=10)),
                ('numerosolapin', models.CharField(max_length=7)),
                ('serial', models.CharField(blank=True, max_length=10, null=True)),
                ('fechaoperacion', models.DateTimeField(unique=True)),
                ('idcausaanulacion', models.ForeignKey(blank=True, db_column='idcausaanulacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ncausaanulacion')),
                ('idsolapin', models.ForeignKey(db_column='idsolapin', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dsolapin')),
                ('idtipooperacionsolapin', models.ForeignKey(db_column='idtipooperacionsolapin', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ntipooperacionsolapin')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dusuario')),
            ],
            options={
                'db_table': 'doperacionsolapin',
            },
        ),
        migrations.CreateModel(
            name='Dincidenciasafis',
            fields=[
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('idincidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('idsolicitudafis', models.ForeignKey(blank=True, db_column='idsolicitudafis', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dsolicitudafis')),
            ],
            options={
                'db_table': 'dincidenciasafis',
            },
        ),
        migrations.CreateModel(
            name='Dciudadanosolapinhist',
            fields=[
                ('idciudadanosolapinhist', models.AutoField(primary_key=True, serialize=False)),
                ('fechaactivado', models.DateTimeField(blank=True, null=True)),
                ('serialsolapin', models.CharField(blank=True, max_length=10, null=True)),
                ('fechadesactivado', models.DateTimeField()),
                ('codigobarra', models.CharField(blank=True, max_length=10, null=True)),
                ('idciudadano', models.ForeignKey(db_column='idciudadano', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dciudadano')),
                ('identificadoranulacion', models.ForeignKey(blank=True, db_column='identificadoranulacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ncausaanulacion')),
                ('idsolapin', models.ForeignKey(db_column='idsolapin', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dsolapin')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dusuario')),
            ],
            options={
                'db_table': 'dciudadanosolapinhist',
            },
        ),
        migrations.CreateModel(
            name='Dciudadanobash',
            fields=[
                ('idexpediente', models.CharField(max_length=20)),
                ('identificadorarea', models.CharField(max_length=150)),
                ('identificadorroluni', models.CharField(max_length=100)),
                ('carnetidentidad', models.CharField(max_length=35)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('primernombre', models.CharField(max_length=100)),
                ('segundonombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primerapellido', models.CharField(max_length=100)),
                ('segundoapellido', models.CharField(blank=True, max_length=100, null=True)),
                ('solapin', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=30, null=True)),
                ('residente', models.BooleanField(blank=True, null=True)),
                ('fecha_registro_modificacion', models.DateTimeField(blank=True, null=True)),
                ('idpersona', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('idestado', models.ForeignKey(blank=True, db_column='idestado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.nestado')),
            ],
            options={
                'db_table': 'dciudadanobash',
            },
        ),
        migrations.AddField(
            model_name='dciudadano',
            name='idpersona',
            field=models.OneToOneField(blank=True, db_column='idpersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dciudadanobash'),
        ),
        migrations.CreateModel(
            name='Doperacionsolicitudhist',
            fields=[
                ('idoperacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaoperacion', models.DateTimeField()),
                ('idestado', models.IntegerField()),
                ('idsolicitudimpresion', models.ForeignKey(db_column='idsolicitudimpresion', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dsolicitudimpresionhist')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dusuario')),
            ],
            options={
                'db_table': 'doperacionsolicitudhist',
                'unique_together': {('idoperacion', 'fechaoperacion')},
            },
        ),
        migrations.CreateModel(
            name='Doperacionsolicitud',
            fields=[
                ('idoperacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaoperacion', models.DateTimeField()),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ntipoestadosolicitud')),
                ('idsolicitudimpresion', models.ForeignKey(db_column='idsolicitudimpresion', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dsolicitudimpresion')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dusuario')),
            ],
            options={
                'db_table': 'doperacionsolicitud',
                'unique_together': {('idoperacion', 'fechaoperacion', 'idsolicitudimpresion')},
            },
        ),
        migrations.CreateModel(
            name='Dcandidatos',
            fields=[
                ('idincidencia', models.OneToOneField(db_column='idincidencia', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='captura_datos.dincidenciasafis')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('idciudbio', models.IntegerField()),
            ],
            options={
                'db_table': 'dcandidatos',
                'unique_together': {('idincidencia', 'idciudbio')},
            },
        ),
        migrations.CreateModel(
            name='Dusuariopermiso',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='captura_datos.dusuario')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('idtipopermiso', models.ForeignKey(db_column='idtipopermiso', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ntipopermiso')),
            ],
            options={
                'db_table': 'dusuariopermiso',
                'unique_together': {('idusuario', 'idtipopermiso')},
            },
        ),
        migrations.CreateModel(
            name='Dhuellaciudadano',
            fields=[
                ('idciudadano', models.OneToOneField(db_column='idciudadano', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='captura_datos.dciudadano')),
                ('huella', models.BinaryField()),
                ('minucia', models.BinaryField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('idtipohuella', models.ForeignKey(db_column='idtipohuella', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.ntipohuellaciudadano')),
            ],
            options={
                'db_table': 'dhuellaciudadano',
                'unique_together': {('idciudadano', 'idtipohuella')},
            },
        ),
        migrations.CreateModel(
            name='Dciudadanosolapin',
            fields=[
                ('idciudadano', models.OneToOneField(db_column='idciudadano', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='captura_datos.dciudadano')),
                ('fecha', models.DateTimeField()),
                ('idsolapin', models.OneToOneField(db_column='idsolapin', on_delete=django.db.models.deletion.DO_NOTHING, to='captura_datos.dsolapin')),
            ],
            options={
                'db_table': 'dciudadanosolapin',
                'unique_together': {('idciudadano', 'idsolapin')},
            },
        ),
    ]
