# Generated by Django 4.2.6 on 2024-06-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captura_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dciudadanosolapin',
            name='idciudadano',
            field=models.OneToOneField(db_column='idciudadano', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='captura_datos.dciudadano'),
        ),
        migrations.AlterField(
            model_name='dciudadanosolapinhist',
            name='idciudadano',
            field=models.ForeignKey(db_column='idciudadano', on_delete=django.db.models.deletion.CASCADE, to='captura_datos.dciudadano'),
        ),
        migrations.AlterField(
            model_name='dhuellaciudadano',
            name='idciudadano',
            field=models.OneToOneField(db_column='idciudadano', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='captura_datos.dciudadano'),
        ),
        migrations.AlterField(
            model_name='dimagenfacial',
            name='idciudadano',
            field=models.OneToOneField(db_column='idciudadano', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='captura_datos.dciudadano'),
        ),
        migrations.AlterField(
            model_name='doperacionsolicitudhist',
            name='idsolicitudimpresion',
            field=models.ForeignKey(db_column='idsolicitudimpresion', on_delete=django.db.models.deletion.CASCADE, to='captura_datos.dsolicitudimpresionhist'),
        ),
        migrations.AlterField(
            model_name='dsolicitudimpresionhist',
            name='idciudadano',
            field=models.ForeignKey(db_column='idciudadano', on_delete=django.db.models.deletion.CASCADE, to='captura_datos.dciudadano'),
        ),
    ]
