# Generated by Django 4.2.6 on 2024-01-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura_datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='prueba',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='dni',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='solapin',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
