# Generated by Django 4.2.6 on 2024-02-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura_datos', '0005_ciudadano_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='fecha_imagen',
            field=models.DateField(null=True),
        ),
    ]
